config/routes.rb
TakeBackApp::Application.routes.draw do

  get "pages/search"

  get "pages/result"

  resources :projects

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root :to => "take_back_app#home"
  get '/signup', to:'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/create', to: 'projects#new'
  get '/work', to: 'projects#index'

  get '/search', to: 'projects#search'

end

app/models/project.rb
#This class is for the 'Project' Model containing some validations as the presence of the attributes
#Also it contains the searhing method

class Project < ActiveRecord::Base
	belongs_to :user
	default_scope order: 'projects.created_at DESC' 
	validates :user_id, presence: true
	validates :title, presence: true
	validates :description, presence: true
	validate :location, presence: true

	#This method is to perform the search functionality on the projects
	
    def self.search(search)
	  if search
	    find(:all, :conditions => ['lower(location) LIKE lower(?)', "%#{search}%"])
	  else
	    find(:all)
	  end
	end

end

app/models/user.rb
#This is the model for a single user, 
#which can be either an administrator or 

class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	has_secure_password
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password_confirmation, presence: true
	validates :password, length: { minimum: 6 }
	has_many :projects, dependent: :destroy

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	  def create_remember_token
		  self.remember_token = User.encrypt(User.new_remember_token)
	  end
end

app/controllers/application_controller.rb
=begin
=This is test
* Comment one
* Comment two
1. enumerated list 1
2. enumberated list 2
=end

class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def search
  end

  def result
  end

end

app/controllers/projects_controller.rb
#This file is for the project controller which ties the different actions with
#corresponding views and models


class ProjectsController < ApplicationController
  
  before_filter :correct_user,   only: :destroy

  #This method shows a single project

  def show
    #if current_user?
     # @project = current_user.projects.find(params[:id])
    #else
      #@project = current_user.projects.find(params[:id])
    #end
    if @user.nil? || current_user.nil?
      @project = Project.find(params[:id])
    end

   end

   #The method which initiates the form of creating a new project
  def new
  end

  #The action of creating the project itself
  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      flash[:warning] = "it didn't work. try again."
      render 'static_pages/home'
    end
  end

#The searching method applied on projects
  def search
     @projects = Project.search(params[:search])
     if @projects.empty?
      flash.now[:warning] = "No result found"
    end
  end
  
    
#Showing the index or total list of projects

  def index
	  #@user = User.find(params[:id])
   if :search_query
      @projects = Project.search(params[:search_query])
       @projects = @projects.sort!{ |x, y| x["created_at"] <=> y["created_at"] }.reverse
     else
       @projects = Project.find(:all, :order => 'projects.created_at').reverse
    end

    # if signed_in?
    #   @projects = current_user.projects.paginate(page: params[:page])
    
    # else
    #   @projects = Project.all
    # end

  end

  def update
    @project = current_user.projects.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = " #{@project.title} was successfully updated!"
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def edit
	@project = current_user.projects.find(params[:id])
  end

  def destroy
    @project.destroy
    flash[:success] = "#{@project.title} was removed!"
    redirect_to work_url
  end

 


private
  def project_params
    params.require(:project).permit(:title, :location, :description)
  end
  def correct_user
      @project = current_user.projects.find(params[:id])
      redirect_to root_url if @project.nil?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  user = User.find_by_email(params[:session][:email].downcase)
	  if user && user.authenticate(params[:session][:password])
	    # Sign the user in and redirect to the user's show page.
	    flash[:success] = 'welcome'
	    sign_in user
      	redirect_back_or user
	  else
	    # Create an error message and re-render the signin form.
	    flash.now[:error] = 'invalid email/password combination' # Not quite right!
	    render 'new'
	  end
	end

	def destroy
		sign_out
		flash[:success] = 'come back soon'
		redirect_to root_url
	end
end

app/controllers/take_back_app_controller.rb
class TakeBackAppController < ApplicationController
  def home
    if signed_in?
      @project  = current_user.projects.build
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user, only: :destroy
  def new
  	@user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "user deleted"
    redirect_to users_url
  end

  def index
    #@user = User.find(params[:id])
    #@projects = @user.projects.paginate(page: params[:page])
    @users = User.all
  end

  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Project.where("user_id = ?", id)
  end

  def show
    @user = User.find(params[:id])
    @projects = @user.projects.paginate(page: params[:page])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "welcome to takeback"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    #@user = User.find(params[:id])
  end

  def update
    #@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  # Before filters
  def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url
      end
    end

  def correct_user
   @user = User.find(params[:id])
   redirect_to(root_url) unless current_user?(@user)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "takeback"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
  	!current_user.nil?
  end

  def current_user=(user)
  	@current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    #@current_user ||= User.find(:all, conditions: { remember_token: remember_token } )
    @current_user ||= User.find_by_remember_token(remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url
      end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/take_back_app_helper.rb
module TakeBackAppHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" >
  <nav>
    <ul>
      <li><%= link_to "takeback", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navgation">
  <div class="navbar-inner">
    <div class="container">
          <%= link_to "takeback", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav">
          
          <li><%= link_to "create", create_path %></li>
          <li><%= link_to "work", work_path %></li>
          <li><%= link_to "search", search_path %></li>
          <% if signed_in? %>

            <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%=@current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "profile", current_user %></li>
              <li><%= link_to "settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "sign out", signout_path, method: "delete" %></li>
            </ul>
            </li>
            </ul>

          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>

      <!--<form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="search for projects">
      </div>
      <button type="submit" class="btn btn-default">submit</button>
    </form>-->

  </div>
</header>

<!--
<nav class="navbar navbar-fixed-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Brand</a>
  </div>


  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
  </div>
  -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--rendering partials-->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/result.html.erb
<h1>Pages#result</h1>
<p>Find me in app/views/pages/result.html.erb</p>

app/views/pages/search.html.erb
<h1>Pages#search</h1>
<p>Find me in app/views/pages/search.html.erb</p>

app/views/projects/_project.html.erb
<!--This is populating the profile page with all the project info. Not clean or clear.-->

<!--<li>
  <span class="description"><%= project.description %></span>
  <span class="title"><%= project.title %></span>
  <span class="location"><%= project.location %></span>
  <span class="timestamp">
    posted <%= time_ago_in_words(project.created_at) %> ago.
  </span>
</li>-->

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1> update your project</h1>

<div class="row">
  <div class="span6 offset3 center">
    <%= form_for(@project) do |f| %>
      

      <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
      </p>

      <p>
      <%= f.label :location %><br>
      <%= f.text_field :location %>
      </p>

      <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
      </p>

     
      <p>
      <%= f.submit "save changes", class: "btn btn-large btn-primary" %>
      </p>

    <% end %>
    </div>
</div>

app/views/projects/index.html.erb
<!-- MY PROJECTS PAGE-->


<div class="span8 center">
 <img src= "http://farm6.staticflickr.com/5499/11358358124_4eedb99478.jpg" width="500" height="299" alt="Boulder Flood Relief Volunteers">


<h1>work on your projects</h1>
<% if signed_in? %>
 <div class="span6 offset3 center">
 	<% @current_user.projects.each do |project| %>
 		<br>
 		<h3><%= link_to project.title, project %><br> 
 		<%= project.location %> <br>
 		<%= link_to "edit", edit_project_path(project) %> <b>/</b>
 		<%= link_to "remove", project, method: :delete, data: { confirm: "are you sure?" } %></h3>
 		
 	<% end %>
 </div>

 <% else %>
 	<h3> <%= link_to "sign in", signin_path %> or <%= link_to "sign up", signup_path %> to work on your projects! </h3>
 <% end %>

<br><br>
 <h2>not enough? <br> <%= link_to "create", new_project_path %> a new project <br> or <%= link_to "search", search_path %> for a project to join.<h2>
 
</div>

app/views/projects/new.html.erb
<!--CREATE a NEW project page-->

<div class="row">
  <div class="span6 offset3 center" >
    <img src= "http://farm8.staticflickr.com/7422/11357206726_407f3282c9.jpg" width="400" height="350" alt="create">
    <h1>create a new project</h1>

    <% if signed_in? %>
      <%= form_for :project, url: projects_path do |f| %>
        <p><br>
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </p>
     
        <p>
         <%= f.label :location %><br>
          <%= f.text_field :location %>
        </p>

       <p>
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </p>
     
        <p>
          <%= f.submit %>
        </p>
    <% end %>

  <% else %>
    <h3> <%= link_to "sign in", signin_path %> or <%= link_to "sign up", signup_path %> to create a new project! </h3>

  <% end %>
  </div>
</div>

app/views/projects/search.html.erb
<div class= "span6 center">
  <img src="http://farm6.staticflickr.com/5486/11349145173_75fb8f01da.jpg" alt="takeback logo"> 
  <h1> search for projects </h1>
  <br>
    <h2><%= form_tag search_path, :method => 'get' do %>
      <p> <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "search by location", :name => nil %>
      </p></h2>
    <% end %>
  
  <br>

<!--THIS code is just showing the user's current projects-->

  <% for project in @projects %>
    <h3><%= link_to project.title, project_path(project) %> in <%= project.location %> <h3>
  <% end %>

</div>



<!--
<h1>Search For Projects</h1>

<div class="row">
  <div class="span6 offset3 center" >

    <% if signed_in? %>
      <%= form_tag("/search", method: "get") do %>
        <%= label_tag(:q, "Search by Location:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
    <% end %>

  </div>
</div>
-->

app/views/projects/show.html.erb
<!-- INDIVIDUAL PROJECT PAGE-->

<div class="span8 center">
<img src=
"http://trc.rmc.org/sites/default/files/rmchealth/library/images/blogs/tools.png" width="480" height="277" alt="toolkit">
<h1><%= @project.title %> <br> in <%= @project.location %></h1>
 <!--<h2> by <%=@project.user_id %> </h2>-->
  <body><i><%= @project.description %></i><br><br></body>

    <!--created: <%= time_ago_in_words(@project.created_at) %> ago!
    
    Created at: <%= (@project.created_at) %> 
      <%= @project = Project.find(params[:id]) %>
    <%= @user = User.find(params[@project.user_id]) %>
    Created By: <%= @user.name %>
   

    -->


    <img src="http://farm6.staticflickr.com/5479/11319934154_d70d1fdde4.jpg" width="500" height="187" alt="ways to work"></a>





</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/take_back_app/home.html.erb
<% provide(:title, 'Home') %>
<div class="center">
 <img src="http://farm6.staticflickr.com/5486/11349145173_75fb8f01da.jpg" alt="takeback logo">	

  <h1 style= "text-align: center, font-family:Helvetica"> takeback</h1>

  	<!--Turn these into links to their pages-->
  	<h3 style= "text-align:center"> ...<%= link_to "create", create_path %> a new project </h3>
  	<h3 style= "text-align:center"> ...<%= link_to "work", work_path %> on a project </h3>
  	<h3 style= "text-align:center"> ...<%= link_to "search", search_path %> for a project </h3>

  	<br><br>
  <!--<%= link_to "sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <br><br>
  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>-->
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "are you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<!--EDIT PROFILE PAGE-->

<% provide(:title, "edit user") %>
<h1>update your settings</h1>

<div class="row">
  <div class="span6 offset3 center">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>


     
      <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      </p>

      <br><br>

      <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
      </p>
      
      <br><br>


      <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
      </p>

      <br><br>

      <p>
      <%= f.label :password_confirmation, "confirm password" %><br>
      <%= f.password_field :password_confirmation %>
      </p>


      <p>
      <br><br>
      <%= f.submit "save changes", class: "btn btn-large btn-primary" %>
      </p>

    <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="span6 offset3 center">
<% provide(:title, 'all users') %>

<h1>all users</h1>

<ul class="users">
  <%= render @users %>
</ul>

</div>

app/views/users/new.html.erb
<!--SIGN UP PAGE-->

<% provide(:title, 'sign up') %>
<h1>sign up <br> for takeback</h1>

<div class="row">
  <div class="span6 offset3 center">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %> <br>
      <%= f.text_field :name %>

      <br><br>

      <%= f.label :email %> <br>
      <%= f.text_field :email %>

      <br><br>

      <%= f.label :password %> <br>
      <%= f.password_field :password %>

      <br><br>

      <%= f.label :password_confirmation %> <br>
      <%= f.password_field :password_confirmation %>

      <br><br>

      <%= f.submit "create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--PROFILE PAGE-->

<% provide(:title, @user.name) %>
<div class="span8 center">
    <img src="http://farm4.staticflickr.com/3715/11348850814_0a48d307ff.jpg" width="500" height="281" alt="Layne, Bob, and Chada">
      <h1>
        <%= @user.name %>'s <%= link_to "projects", work_path %>
      </h1>
</div>


<!--
  <div class="span8 center">
    <% if @user.projects.any? %>
      <h3>Projects (<%= @user.projects.count %>)</h3>
      <ol class="projects">
        <%= render @projects %>
      </ol>
      <%= will_paginate @projects %>
    <% end %>
  </div>
  